
<div class="abc">
		<a href="games.php?letter=0-9">0-9</a>
		<a href="games.php?letter=A">A</a> 
		<a href="games.php?letter=B">B</a> 
		<a href="games.php?letter=C">C</a> 
		<a href="games.php?letter=D">D</a> 
		<a href="games.php?letter=E">E</a> 
		<a href="games.php?letter=F">F</a> 
		<a href="games.php?letter=G">G</a> 
		<a href="games.php?letter=I">I</a>
	    <a href="games.php?letter=J">J</a>  
		<a href="games.php?letter=K">K</a> 
		<a href="games.php?letter=L">L</a> 
		<a href="games.php?letter=M">M</a> 
	    <a href="games.php?letter=N">N</a> 
		<a href="games.php?letter=O">O</a> 
		<a href="games.php?letter=P">P</a> 
		<a href="games.php?letter=Q">Q</a> 
		<a href="games.php?letter=R">R</a> 
		<a href="games.php?letter=S">S</a> 
		<a href="games.php?letter=T">T</a> 
		<a href="games.php?letter=U">U</a> 
		<a href="games.php?letter=V">V</a> 
		<a href="games.php?letter=W">W</a> 
		<a href="games.php?letter=X">X</a> 
		<a href="games.php?letter=Y">Y</a> 
		<a href="games.php?letter=Z">Z</a>
		</div> 
